### PR TITLE
Propose adding a Editorconfig

### PR DESCRIPTION
**Pull request by PhilETaylor**
Proposing adding a `.editorconfig` standard like the Joomla 4 version

### CODE REVIEW

**Comment by nibra** [comment]
Makes sense. Would you mind to add this also to the other packages ?

**Comment by PhilETaylor** [comment]
Do you mean all 49 joomla-framework packages?

**Comment by nibra** [comment]
Yes, but it's ok, if you don't want to, then it just takes longer... ;)

**Comment by PhilETaylor** [comment]
Luckily this works... 

```
curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/joomla-framework/repos?per_page=100" | jq -r ".[].ssh_url" | xargs -L1 git clone
```

**Comment by PhilETaylor** [comment]
done!

**Comment by nibra** [comment]
Thank you very much! Especially these boring nitty gritty tasks need a lot of love!

**Pull request merged**
